
import React from 'react';

const albumInfo = {
  title: "The Book of Tess",
  writer: "Sarah C.",
  releaseDate: "August 19th, 2025",
  coverUrl: "https://s3.amazonaws.com/gather.fandalism.com/800x800%2D10168680%2D%2D017F168A%2D1372%2D4B7D%2DA98872A92274AB70%2D%2D0%2D%2D6966652%2D%2DTHEBOOKOFTESS.472Z.jpg",
  appleMusicUrl: "https://music.apple.com/us/album/the-book-of-tess/1834989095",
  spotifyUrl: "https://open.spotify.com/album/4V8q7sKUgky8t4z4UyM4OE?si=ED9HSwxEQquDjCEKv5hpsg",
  spotifyUri: "spotify:album:4V8q7sKUgky8t4z4UyM4OE",
};

const tracklist = [
    { num: 1, title: "The Light", duration: "2:55" },
    { num: 2, title: "We Shall Fly", duration: "3:13" },
    { num: 3, title: "Cathedral of Green", duration: "3:15" },
    { num: 4, title: "Your Heart", duration: "2:54" },
    { num: 5, title: "Sonic Boom of Love", duration: "2:49" },
    { num: 6, title: "Fields of Faded Green", duration: "3:06" },
    { num: 7, title: "Our Line & Time (feat. Henry Thorton)", duration: "3:04" },
    { num: 8, title: "One to Many", duration: "3:00" },
    { num: 9, title: "Algorhythm Love", duration: "2:42" },
    { num: 10, title: "Big City", duration: "3:03" },
    { num: 11, title: "The Book of Tess", duration: "2:51" },
];

const singles = [
  { title: "We Shall Fly", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "Cathedral Of Green", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "Our Line & Time (Feat. Henry Thorton)", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "Your Heart", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "Sonic Boom of Love", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "Fields of faded green", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "One to many", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "algorhythm love", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "big city", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" },
  { title: "the light", spotifyUrl: "https://open.spotify.com/artist/5QaZEijSCxPjPf3JXNLOgq", appleMusicUrl: "https://music.apple.com/us/artist/tessa-mae/1834687808" }
];


const LatestReleasePage: React.FC = () => {
  return (
    <div className="container mx-auto px-6 animate-slide-in-up pb-16">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tight select-none">Latest Release</h1>
        </div>

        <div className="bg-gray-900/50 backdrop-blur-md border border-white/10 rounded-2xl shadow-2xl p-6 sm:p-8 flex flex-col md:flex-row gap-8">
          {/* Left Side: Album Art & Album Links */}
          <div className="md:w-1/3 flex-shrink-0">
            <img 
              src={albumInfo.coverUrl} 
              alt={`Album cover for ${albumInfo.title}`} 
              className="rounded-lg shadow-2xl w-full aspect-square pointer-events-none select-none"
            />
            <h2 className="text-3xl font-bold text-center mt-6 select-none">{albumInfo.title}</h2>
            <p className="text-center text-gray-400 mt-1 select-none">generated by {albumInfo.writer}</p>
            <p className="text-center text-gray-400 text-sm mt-1 select-none">{albumInfo.releaseDate}</p>
            <div className="mt-6 flex gap-3">
              <a 
                href={albumInfo.appleMusicUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full flex items-center justify-center gap-2 font-semibold rounded-lg py-3 px-6 bg-gray-700 hover:bg-gray-600 transition-colors duration-300 select-none"
              >
                <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/Apple_logo_white.svg" alt="Apple Music" className="h-5 w-auto aspect-[1/1]" /> Apple Music
              </a>
              <a 
                href={albumInfo.spotifyUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="w-full flex items-center justify-center gap-2 font-semibold rounded-lg py-3 px-6 bg-gray-700 hover:bg-gray-600 transition-colors duration-300 select-none"
              >
                <img src="https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_White.png" alt="Spotify" className="h-5" />
              </a>
            </div>
          </div>

          {/* Right Side: Tracklist */}
          <div className="md:w-2/3">
            <div className="space-y-1">
                {tracklist.map((track) => (
                    <div key={track.num} className="flex justify-between items-center py-2 px-3 rounded-md hover:bg-white/5 transition-colors">
                        <div className="flex items-center gap-4">
                            <span className="text-gray-500 w-6 text-right select-none">{track.num}</span>
                            <p className="text-white font-medium select-none">{track.title}</p>
                        </div>
                        <p className="text-gray-400 text-sm font-mono select-none">{track.duration}</p>
                    </div>
                ))}
            </div>
          </div>
        </div>

        {/* Singles Section */}
        <div className="mt-16">
          <h2 className="text-3xl font-bold text-center mb-8 select-none">Singles</h2>
          <div className="space-y-4">
            {singles.map((song) => (
              <div key={song.title} className="bg-gray-900/50 backdrop-blur-md border border-white/10 rounded-xl shadow-lg p-4 flex justify-between items-center">
                <p className="font-semibold text-lg text-white select-none">{song.title}</p>
                <div className="flex gap-3">
                  <a
                    href={song.appleMusicUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-center gap-2 font-semibold rounded-lg py-2 px-4 bg-gray-700 hover:bg-gray-600 transition-colors duration-300 select-none text-sm"
                  >
                    <img src="https://upload.wikimedia.org/wikipedia/commons/3/31/Apple_logo_white.svg" alt="Apple Music" className="h-4 w-auto aspect-[1/1]" /> Apple Music
                  </a>
                  <a
                    href={song.spotifyUrl}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center justify-center gap-2 font-semibold rounded-lg py-2 px-4 bg-gray-700 hover:bg-gray-600 transition-colors duration-300 select-none text-sm"
                  >
                    <img src="https://storage.googleapis.com/pr-newsroom-wp/1/2018/11/Spotify_Logo_RGB_White.png" alt="Spotify" className="h-4" />
                  </a>
                </div>
              </div>
            ))}
          </div>
        </div>

      </div>
    </div>
  );
};

export default LatestReleasePage;